apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  labels:
    app: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: 339712888957.dkr.ecr.us-east-1.amazonaws.com/pacman-shalom2025:0414d70
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_SERVICE_HOST
              value: "mongodb"
            - name: MONGO_DATABASE
              value: "pacman"

